server_port = 4446
code_theme = "base16-eighties.dark"
req_limit_per_sec = 50
browser_cache_max_age = 3600

[cache]
limit_size = 10485760
post_cache_weight = 0.8
post_nav_weight = 0.3
post_page_rendered = 0.5
post_metadata = 0.1

[limits]
recent_posts = 4
categories = 5
series = 5
plain_posts_list = 15

[templates]
error = "error.html"
post = "post.html"
post_list = "post_list.html"
index = "index.html"

[scss]
"style.css" = [
  "base.scss",
  "banner.scss",
  "nav.scss", 
  "post.scss", 
  "specific.scss", 
  "error.scss",
]
