server_port = 4446
code_theme = "base16-eighties.dark"
req_limit_per_sec = 50
browser_cache_max_age = 3600

scss_dir = "scss"
scripts_dir = "scripts"
templates_dir = "templates"
posts_registry = "registry.toml"
posts_dir = "posts"

site_config_file = "site.toml"
add_assets = [
  "images"
]

[limits]
recent_posts = 4
categories = 5
series = 5
plain_posts_list = 15

[templates]
error = "error.html"
post = "post.html"
post_list = "post_list.html"
index = "index.html"

[scss]
"style.css" = [
  "base.scss",
  "banner.scss",
  "nav.scss", 
  "post.scss", 
  "specific.scss", 
  "error.scss",
]
"print.css" = [
  "print.scss",
]
