name = "Litchi Pi"
author_name = "Litchi Pi"
author_email = "litchi.pi@proton.me"
base_url = "https://litchipi.site"
description = """
Rust Software engineer, graduated in electronics and embedded systems, with side interests in information security as well.
"""

welcome_message = """
Welcome on my blog, I write articles about anything I find interesting, and try to get an interesting scope instead of write "Yet another X article".

I do have other passions and hobbies, but it's unlikely that I'll write about it. I'd be happy to chat with anyone about pretty much anything, so feel free to reach me to have a chat ! :-)
"""

copyrights = "Content released under a Creative commons CC BY-NC license"
og_image = "images/og_banner.png"

blog_src = "https://github.com/litchipi/blog"
blog_engine_src = "https://github.com/litchipi/ecoweb"

[social]
github = "https://github.com/litchipi/"
mastodon = "https://fosstodon.org/@litchipi"
email = "mailto:litchi.pi@proton.me"

[webring]
name = "Experimental Math & Programming Ring"
previous = "https://scatter.flowers"
next = "https://themathjester.com"
