# TODO  French hireme title
title = "Travaillons ensemble"
introduction = """
  Voici une brève introduction de ce que je fais et *pourquoi* je le fais.  
  Pour parler en détail de toute idée avec vous, je suis à votre entière disposition !

  Envoyez moi un e-mail dès à présent à `litchi.pi@proton.me` !
"""

[why]
title = "Valoriser nos différences"
# TODO  French hireme translation
body = """
  TODO  
"""

[how]
title = "TODO"
body = """
  TODO  
"""

[what]
title = "TODO"
body = """
  TODO  
"""

[outro]
title = "TODO"
body = """
  TODO  
"""
