title = "Hire me"

introduction = """
  In need of help for a project ?  
  Here is what I propose, feel free to contact me so we can chat about it in depth !

  Email me today at `litchi.pi@proton.me` !
"""

[why]
title = "Empowering our differences"
body = [
  """
    Against the monopoly of big software companies in the cyberspace,
    **my mission** is to let people *feel free* with their tools,
    enjoy *an alternative* for the crappy software products that cripple our field.
  """,
  """
    Everyone is different, have different ways to think, interact, do,
    and *I believe* that the software should **adapt to the people**,
    not the other way around.
  """,
  """
    Wether you are visually impaired, eccentric, old, artistic, autistic,
    geek, dyslexic, or none of all this,
    there is a software we can *build together* to fit your vision,
    your way, your world.
  """
]

# [[why.body]]
# title = "Against the monopoly"
# text = """of big software companies in the cyberspace,
# **my mission** is to let people *feel free* with
# their tools, enjoy *an alternative* for the crappy software products that cripple our field.  "

[how]
title = "Human-first software crafting"
body = [
  """
    Everything is possible, a whole new way to use a computer can be redefined from
    *your vision*.  
    Tell me what holds you from feeling finally free on your computer environment,
    your needs and desires, and I will craft a software for it.
  """,
  """
    Only after completely **understanding** someone else's view,
    can someone create something that fits their vision, who they are.  
    For this reason, the whole process is centered around **you**.
  """,
  """
    After being sure all of your criterias are defined and addressed in the proposed
    solution, a piece of software is crafted to *fit exactly* all of them.
  """
]

[what]
title = "Better tools, greater efficiency"
body = [
  """
    *People's time* is the most expensive resource a company spend,
    *don't waste it* !  

    Tools have a big impact on people's *happiness at work*,
    improving it means optimizing how the core system of your company performs.
  """,
  """
    While ensuring the *high quality* of the tool created,
    the implementation will also think of the future, when some maintenance or
    improvements will be needed.  
    Security, maintenability, performances, extensibility, these are the priorities
    that will drive the craft of your tool.
  """,
  """
    Wether your are a CEO, a Team lead, or a worker, improving your work environment
    can be *what is missing* to reach a significant ergonomy, performance, to
    get through a tough period, or handle an overly productive one.  
  """,
  """
    The finest swordmaker **isn't able** to make a butter knife
    without a furnace.
  """
]

[outro]
title = "Interested ?"
body = """
  Contact me today at `litchi.pi@proton.me` !  
  Let's build together a work environment that empowers your business !
"""
