title = "Sondage"
disclamer = "Les données de ce formulaire sont stockées de façon anonyme, seuls vos réponses sont conservées, aucune autre donnée n'est collectée."

[lang]
yes = "Oui"
no = "Non"

[numeric_or_not]
text = "Êtes-vous un professionnel du secteur du numérique ou non ?"
type = "yes_or_no"

# Questions for numeric pros
[question.numeric-pro.2-experience-in-field]
text = "Depuis combien de temps (environ) travaillez vous dans le numérique ?"
type = "number"

[question.numeric-pro.3-experience-in-field]
text = "Depuis combien de temps (environ) travaillez vous dans le numérique ?"
type = "number"

[question.numeric-pro.4-experience-in-field]
text = "Depuis combien de temps (environ) travaillez vous dans le numérique ?"
type = "number"

[question.numeric-pro.5-experience-in-field]
text = "Depuis combien de temps (environ) travaillez vous dans le numérique ?"
type = "number"

[question.numeric-pro.6-experience-in-field]
text = "Depuis combien de temps (environ) travaillez vous dans le numérique ?"
type = "number"


# Questions for not numeric pros
[question.not-numeric.2-what-field]
text = "Dans quel secteur d'activité travaillez-vous ?"
type = "text"

[question.not-numeric.3-what-field]
text = "Dans quel secteur d'activité travaillez-vous ?"
type = "text"

[question.not-numeric.4-what-field]
text = "Dans quel secteur d'activité travaillez-vous ?"
type = "text"

[question.not-numeric.5-what-field]
text = "Dans quel secteur d'activité travaillez-vous ?"
type = "text"
