title = "Sondage"
disclamer = "Les données de ce formulaire sont stockées de façon anonyme, seuls vos réponses sont conservées, aucune autre donnée n'est collectée."
first_question_set = "intro"

# TODO List of str

[lang]
yes = "Oui"
no = "Non"
send_button = "Envoyer"
email_text = """
Si <a href="/hireme/fr">mon project</a> vous intéresse,
entrez votre e-mail et je vous recontacterai"""
email_note = """Ceci est totalement optionnel.<br/>
L'adresse e-mail collectée ne sera pas utilisé avec abus, et ne sera partagé avec personne."""
email_lbl = "Adresse e-mail:"

[question.intro.numeric_or_not]
text = "Êtes-vous un professionnel du secteur du numérique ou non ?"
type = "yes_or_no"
addq_yes = "numeric-pro"
addq_no = "not-numeric"

# Questions for numeric pros
[question.numeric-pro.2-experience-in-field]
text = "Depuis combien de temps (environ) travaillez vous dans le numérique ?"
type = "number"
min = 0
max = 70
label_after = "années"

[question.numeric-pro.3-rse-sensibility]
text = "À quel point êtes vous sensible aux problématiques de RSE ? (Écologie, inclusion, accessibilité, ...)"
type = "range"
threshold = { "Peu sensible" = 2, "Neutre" = 5, "Sensible" = 7, "Très sensible" = 10 }
min = 0
max = 10

[question.numeric-pro.4-quality-sensibility]
text = "Préférez-vous la qualité, ou la facilité de mise en oeuvre d'une solution ?"
type = "range"
threshold = { "A Something" = 5, "B Aoakze" = 7, "Final" = 10 }
min = 0
max = 100

# Questions for not numeric pros
[question.not-numeric.2-what-field]
text = "Dans quel secteur d'activité travaillez-vous ?"
type = "text"

[question.not-numeric.3-ease-with-numeric]
text = "À quel point êtes vous à l'aise avec les outils du numérique ?"
type = "range"
threshold = { "A Something" = 5, "B Aoakze" = 7, "Final" = 10 }
min = 0
max = 10

[question.not-numeric.4-rse-sensibility]
text = "À quel point êtes vous sensible aux problématiques de RSE ?"
note = "RSE = Responsabilité Social des Entreprises (Écologie, inclusion, accessibilité, ...)"
type = "range"
threshold = { "Peu sensible" = 2, "Neutre" = 5, "Sensible" = 7, "Très sensible" = 10 }
min = 0
max = 10

[question.not-numeric.test]
text = "Test"
type = "yes_or_no"
addq_yes = "testset"

[question.testset.toto]
text = "tutu"
type = "yes_or_no"
addq_no = "azekl"

[question.azekl.tata]
text = "pok"
type = "yes_or_no"
